### ISSUE TITLE
HTTP Server freezes with multi-packet requests

### ISSUE THREAD

**Issue by favreau** [HBPVIS/ZeroEQ#175] opened 2016-07-20 15:11 UTC
In the Server::Impl::process method, the request.complete() returns true on when the first packet is received. If the request arrives in many packets, only the first one is considered, and the message is trucated. The error is then propagated to the JSON parser, that in the end freezes the HTTP interface.

I worked around the problem by ignoring such requests, but this is of course not acceptable.

```
      if( consumed != msgSize )
                    return; // incomplete message, ignore
```

I have the feeling that the problem is in the underlying http lib that is not properly setting the complete flag.

**Comment by eile** [comment] 2016-08-15 12:48
@favreau : Trying to reproduce, see 	aea2e2b.

I've verified that the http::Server receives multiple messages, and the .complete() is handled correctly. My guess it's not the multi-packet causing the bug, but some payload which is either corrupt, or causes the http parser to complete() prematurely. Do you have any reproducer?

**Comment by favreau** [comment] 2016-08-15 13:28
@eile The problem is random and can be difficult to reproduce. It is more frequent over the wifi though. A python script would probably make it easy to debug the issue. Something like:
{code}
import requests
import json
payload = {...}
while True:
  r = requests.put('http://...', data=json.dumps(payload))
{code}
And breakpoint in case consumed != msgSize

**Comment by eile** [comment] 2016-08-16 13:45
Can't reproduce - I'll need more information on what triggers this bug.

**Comment by favreau** [comment] 2016-08-16 14:02
In any case, the most important issue is the freeze of the HTTP interface. I am also having trouble reproducing the problem for some reason. Maybe this was related to some network issues we had at the time. The reproducer is only about sending truncated JSON messages and make sure that it is properly handled by the HTTP server.

**Comment by favreau** [comment] 2016-08-17 14:06
For some reason, the problem is back again today... don't ask me why. Starting a server on Dalek and accessing it from a remote client (ideally wifi) should help. I also noticed that it is more easily reproducable from a client running on our openstack virtual machines.

**Comment by tribal-tec** [comment] 2016-11-22 10:10
Most probably resolved with https://github.com/HBPVIS/ZeroEQ/pull/184.
Close if you agree and confirm.

**Closed** 2017-01-19 19:50 UTC
Labels: bug
